simples/filmes/app.py
from flask import Flask

from routes.home import home_route
from routes.cadastro import cadastro_route
from routes.preferencias import pref_route
from routes.cookies import cookies_route
from routes.recomendar import recomendar_route

app = Flask(__name__)

app.register_blueprint(home_route)
app.register_blueprint(cadastro_route, url_prefix='/cadastro')
app.register_blueprint(pref_route, url_prefix='/preferencias')
app.register_blueprint(cookies_route, url_prefix='/cookies')
app.register_blueprint(recomendar_route, url_prefix='/recomendar')

if __name__ == '__main__':
    app.run(debug=True)

simples/filmes/routes/cadastro.py
from flask import Blueprint, render_template

cadastro_route = Blueprint('cadastro', __name__)

@cadastro_route.route('/')
def cadastro_page():
    return render_template('cadastro.html')

simples/filmes/routes/cookies.py
from flask import Blueprint, request, make_response, url_for, redirect

cookies_route = Blueprint('cookies', __name__)

@cookies_route.route('/salvar-preferencias', methods = ['POST'])
def salvar_preferencias():
    validade = 7 * 24 * 60 * 60 # 7 dias
    response = make_response(redirect(url_for('preferencias.pref_page')))
    response.set_cookie('notificacoes', 'Não', validade)
    if 'notificacoes' in request.form:
        response.set_cookie('notificacoes', 'Sim', validade)
    if request.form['genero']:
        response.set_cookie('genero', request.form['genero'], validade)

    response.set_cookie('nome', request.form['nome'], validade)
    
    

    return response

simples/filmes/routes/home.py
from flask import Blueprint, render_template

home_route = Blueprint('home', __name__)

@home_route.route('/')
def home_page():
    return render_template('index.html')

simples/filmes/routes/preferencias.py
from flask import Blueprint, render_template, request

pref_route = Blueprint('preferencias', __name__)

@pref_route.route('/')
def pref_page():
    nome = request.cookies.get('nome')
    genero = request.cookies.get('genero')
    notificacoes = request.cookies.get('notificacoes')
    
    return render_template('preferencias.html', nome = nome, genero = genero, notificacoes = notificacoes)

simples/filmes/routes/recomendar.py
from flask import Blueprint, render_template, request

recomendar_route = Blueprint('recomendar', __name__)

@recomendar_route.route('/')
def recomendar_page():
    filmes = {
        "Ação": [
            "Vingadores: Ultimato", 
            "Mad Max: Estrada da Fúria", 
            "John Wick", 
            "Duro de Matar", 
            "Gladiador"
        ],
        "Comédia": [
            "O Máskara", 
            "Superbad - É Hoje", 
            "A Mulher Invisível", 
            "As Branquelas", 
            "Apertem os Cintos... O Piloto Sumiu!"
        ],
        "Drama": [
            "A Espera de um Milagre", 
            "O Poderoso Chefão", 
            "Forrest Gump", 
            "Os 12 Macacos", 
            "O Clube da Luta"
        ],
        "Ficção": [
            "Interestelar", 
            "Blade Runner 2049", 
            "Matrix", 
            "2001: Uma Odisseia no Espaço", 
            "Star Wars: Uma Nova Esperança"
        ],
        "Terror": [
            "O Iluminado", 
            "Hereditary", 
            "A Noite dos Mortos-Vivos", 
            "Atividade Paranormal", 
            "Invocação do Mal"
        ]
    }
    recomendacoes = None
    genero = None

    if not request.args: # pagina recomendar/, sem string de consulta
        genero = request.cookies.get('genero')

    else: # depois de selecionar o formulário
        genero = request.args.get('genero')
        if genero == 'favorito':
            genero = request.cookies.get('genero')
        recomendacoes = filmes[genero]
    return render_template('recomendacoes.html', recomendacoes = recomendacoes, favorito=genero)

simples/filmes/templates/cadastro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/main.css') }}">
</head>
<body>
    <header>
        <h1>Cadastre sua preferência de filmes</h1>
    </header>
    <main>
        <form method="post"  action="{{ url_for('cookies.salvar_preferencias') }}">
            <div class="container">
                <label for="nome">Nome de usuário</label>
                <input type="text" name="nome" required>
                <label for="genero">Gênero favorito</label>
                <select name="genero" id="" required>
                    <option value="" selected>Selecione um Gênero</option>
                    <option value="Ação">Ação</option>
                    <option value="Comédia">Comédia</option>
                    <option value="Ficção">Ficção</option>
                    <option value="Terror">Terror</option>
                    <option value="Drama">Drama</option>
                </select>
                <label for="notificacoes">Deseja receber notificações por email? <input type="checkbox" name="notificacoes" id=""></label>
                
                <button type="submit">Enviar</button>
            </div>
        </form>
    </main>
</body>
</html>

simples/filmes/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Filmes</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/main.css') }}">
</head>
<body>
    <a href="{{ url_for('cadastro.cadastro_page') }}">
        <div class="botao">Cadastrar preferência</div>
    </a>
    <a href="{{ url_for('preferencias.pref_page') }}">
        <div class="botao">Visualizar preferência</div>
    </a>
    <a href="{{ url_for('recomendar.recomendar_page') }}">
        <div class="botao">Ver recomendações de filmes</div>
    </a>
</body>
</html>

simples/filmes/templates/preferencias.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Preferências</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/main.css') }}">
</head>
<body>
    {% if nome and genero and notificacoes %}
        <header>
            <h1>Suas preferências</h1>
        </header>
        <main>
            <div class="container">
                <ul>
                    <li><strong>Nome de usuário: </strong>{{ nome }}</li>
                    <li><strong>Gênero Favorito: </strong> {{ genero }}</li>
                    <li><strong>Irá receber notificações? </strong> {{ notificacoes }}</li>
                </ul>
            </div>
        </main>
        
    {% else %}
        <header>
            <h1>Você não está cadastrado</h1>
        </header>
        <a href="{{ url_for('cadastro.cadastro_page') }}">
            <div class="botao">Cadastre-se</div>
        </a>
    {% endif %}
</body>
</html>

simples/filmes/templates/recomendacoes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Recomendações</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/main.css') }}">
</head>
<body>
    <header><h1>Recomendações</h1></header>
    <main>
        {% if recomendacoes %}
            <div class="container">
                <h2>Filmes de {{ favorito }}</h2>
                <ul>
                {% for filme in recomendacoes%}
                    <li>{{ filme }}</li>
                {% endfor %}
                </ul>    
            </div>
            
        {% else %}
            <form action="">
                <div class="container">
                    <select name="genero" required>
                        <option value="" selected>Gênero</option>
                        <option value="Ação">Ação</option>
                        <option value="Comédia">Comédia</option>
                        <option value="Drama">Drama</option>
                        <option value="Ficção">Ficção</option>
                        <option value="Terror">Terror</option>
                        {% if favorito %}
                            <option value="favorito">Meu gênero favorito</option>
                        {% endif %}
                    </select>
                    <button>Ver recomendações</button>
                </div>
            </form>
        {% endif%}
    </main>
</body>
</html>